language: node_js
cache:
  directories:
  - node_modules
node_js:
- 8
- 10
- node
before_install:
  - npm install -g greenkeeper-lockfile@1
before_script:
- npm prune
- greenkeeper-lockfile-update
after_script:
- npm run coverage
- cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  > /dev/null 2>&1
- greenkeeper-lockfile-upload
env:
  global:
    secure: j0fBlKzmu67LgK2aFzLogmK/lXA8r7UkQ0lq/j8telZZndci3aldlWAF0eL+cx2RUemIndt2tRm5ERPq1izUbuy4VRoQauzJVImiXdnjsirBIcXz7nywMapu7foZJmINl+cSJde6EsiODb/8xr1SHDSfX6J3NQwM2e1+MFcNuzFiR2g14z7Vn4rtO0BzG8PjH8+wVa0BymJdh0qiSi9IhIyltxiDt1KOUjmprNJ1Gr+Gvgickh/4UH4q2sZEPXSjITMSFESKfb8hRUhqpYlnEaNEiFYV4fN+ae1GlSiJPbmpSYIpmyKQSuklN7QM3ebSVFTtA1GmAfgjDi6OgJDKQS2niWQTMn/f0r+RMGPo7gXuD23oAX7wvcfIxQfhpIfKFVmr0i5w8Zgqwurcr6zA8gRxHWRylbm8F2QIUfLq/KPzF6NKsCu/OtFpk6wkIQ99k+eVuPCRCveJPkMP2tdEnTIDRu90zVZLLsvlFFNRsko2ACB6dxFBV5h2V8L1qHJXSu1RETWZ7EnmgCVFpewPGOngV7Zwq7sH4fG5spFgF4Zq5VdpqJFdBHFPjT05SEqZgCSs0faexOIq4ple7DloGlRVmGk8mmFcKRQNOu1bpQJg4L18R+FN0PFw2EqRDogcc09uv4BLPvHep6AjTXdJe0dDwGsM/AKFJJxBoerze5I=
